#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Apr 13 18:26:24 EDT 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ctrlr_tb_behav -key {Behavioral:sim_ctrlr:Functional:ctrlr_tb} -tclbatch ctrlr_tb.tcl -log simulate.log"
xsim ctrlr_tb_behav -key {Behavioral:sim_ctrlr:Functional:ctrlr_tb} -tclbatch ctrlr_tb.tcl -log simulate.log

